# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc3966abd78c4833fadc302e764d4e0d90dcb7a88935bc6a5ea1c90753b4165ebbbc1bf9d8914d3576a2368c5b9538090f3f15b331cb717f5608532fe0153273

test:
  secret_key_base: d097174871acc723a39a70f9e878b42b6d640357a0e85372c9c14550113bd966cd23259364e37e15778cc05e1c87af5f61508b35863f0e365e3f595420d98a7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
